version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ipamdb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipamdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
